---
- hosts: Proxmox
  tasks:
  - name: Get VM current state 
    community.general.proxmox_kvm:
      api_user: root@pam
      api_password: RpcYoHi6Kb9y
      api_host: 167.114.172.172
      name: zabbix-srv
      node: ns514447
      state: current
