---
- hosts: Proxmox
  tasks:
  - proxmox:
      api_user: root@pam
      api_password: RpcYoHi6Kb9y
      api_host: 167.114.172.172
      vmid: zabbix-srv
      node: ns514447
      state: restarted
